pinout-xyz/Pinout.xyz

src/en-GB/overlay/ground.md

17: ona the -> on the
20: convinient -> convenient
21: closes -> closest

fixed a few spelling errors

---

src/de-DE/overlay/display-o-tron-hat.md
src/de-DE/overlay/display-o-tron.md
src/de-DE/overlay/dots.md
src/de-DE/overlay/explorer-hat-pro.md
src/de-DE/overlay/i2c.md
src/de-DE/overlay/piano-hat.md
src/de-DE/overlay/pibrella.md
src/de-DE/overlay/piglow.md
src/de-DE/overlay/skywriter-hat.md
src/de-DE/overlay/unicorn-hat.md

more translations to german

---

src/fr-FR/index.md

Make it consistent with all the other languages

Fix header-level

---

generate-html.py
generate-json.py
pinout.py
serve.py
urlmapper.py

Code tidyup

---

generate-html.py

This prevents the flags being displayed in a different random order
every time you run make!

Explicitly sort the languages

---

src/en/overlay/explorer-hat.md

Edit to match Explorer HAT Pro

Minor typo

---

generate-html.py
src/de/settings.yaml
src/en/settings.yaml
src/es/settings.yaml
src/fr/settings.yaml
src/it/settings.yaml
src/tr/settings.yaml

Tidy up the generation of the "details" bullet-point list
See the discussion in https://github.com/Gadgetoid/Pinout2/commit/cdf2697c981a47ded0406773e0ab8290a8089d44

Fixup details

---

src/de/overlay/rtk-000-001.md
src/de/overlay/sense-hat.md
src/de/overlay/spi.md
src/de/overlay/traffic-hat.md
src/de/overlay/uart.md
src/de/overlay/wiringpi.md
src/de/settings.yaml

So, I guess these are the last translations needed to have a fully translated german site.
Now let's wait for the feedback from the first german users...

last initial translations to german

---

convert.py
generate-json.py
markjaml.py
pinout.py
serve.py
tools/generate-defines.py
urlmapper.py

Similar to what @Gadgetoid did in https://github.com/Gadgetoid/Pinout2/commit/5c7963b2d3f42df4130e1c7b4cc34fe9b2450e3d but now for *all* Python files :-)

Minor code reformatting

---

make_all.sh

Should make it easier to test that all languages still build, before submitting any PRs.

Script to build all languages

---

src/en/overlay/1-wire-plus.md
src/en/overlay/adc-differential-pi.md
src/en/overlay/adc-pi-plus.md
src/en/overlay/adc-pi-zero.md
src/en/overlay/io-pi-plus.md
src/en/overlay/rtc-pi-plus.md
src/en/overlay/serial-pi-plus.md

I have added 7 of our boards to the src/en/overlay folder.  I was not sure if anything else needs to be added for you to include them on the website.
Please let me know if I need to update any other files.

Added new boards from AB Electronics UK

---

draft/overlay/analog-zero.md
draft/overlay/template.md

Analog Zero overlay for review

---

draft/overlay/template.md

Added RasPiO Analog Zero based on the template.md

RasPiO Analog Zero overlay

---

src/en/index.md

Clarify who "Gordon" is

---

src/en/overlay/rtk-000-001.md

Maybe you want to use both instead? idk

Use GPIO Zero for RTK MCB

---

src/es/index.md

Updated the Spanish index.md file, according to the new English index.md
file

Updated index.md (Spanish)

---

src/en/overlay/piborg-ledborg.md

Modify LEDBorg code example to work with Python2

---

README.md

Mainly adding links and fixing typos

Various enhancemnets to README.md

---

src/es/translate/adafruit-pitft-35-plus.md
src/es/translate/automation-phat.md
src/es/translate/justboom-amp-hat.md
src/es/translate/justboom-amp-zero.md
src/es/translate/justboom-dac-hat.md
src/es/translate/justboom-dac-zero.md
src/es/translate/justboom-digi-hat.md
src/es/translate/justboom-digi-zero.md
src/es/translate/pantilt-hat.md
src/es/translate/papirus-hat.md
src/es/translate/papirus-zero.md

11 boards translated (adafruit pitft to papirus zero) Spanish

11 boards translated (adafruit pitft to papirus zero) Spanish

---

src/es/translate/adafruit-animated-eyes-bonnet.md
src/es/translate/adafruit-gps-hat.md
src/es/translate/adafruit-pigrrl-pcb.md
src/es/translate/adafruit-speaker-bonnet.md

Hello.
This is my first translation so I'm hoping for some feedback.
I'll try to translate the rest in a couple of days.

Translate 4 boards to Spanish

---

src/es/translate/adafruit-16x2-lcd.md
src/es/translate/adafruit-arcade-bonnet.md
src/es/translate/adafruit-motor-hat.md
src/es/translate/adafruit-pi-rtc.md
src/es/translate/adafruit-rgb-matrix-hat.md
src/es/translate/adafruit-tft-kippah.md
src/es/translate/phat-beat.md
src/es/translate/pi-cap.md
src/es/translate/picade-hat.md
src/es/translate/pisupply-pi-poe.md
src/es/translate/rabbitmax-flex.md
src/es/translate/rainbow-hat.md
src/es/translate/scroll-phat-hd.md
src/es/translate/speaker-phat.md
src/es/translate/uugear-zero2go.md
src/es/translate/waveshare-adda-board.md

All the boards A-W (2017/03/16) translated (Spanish).

Boards A-W translated (Spanish)

---

src/es/translate/adafruit-joybonnet.md
src/es/translate/button-shim.md
src/es/translate/emlid-navio2.md
src/es/translate/energenie-pi-mote.md
src/es/translate/fepi-audio-z.md
src/es/translate/fourletter-phat.md
src/es/translate/gertvga-666.md
src/es/translate/hyperpixel.md

Boards A to F have been translated to Spanish

Boards A-F translated (Spanish)

---

src/fr/translate/nadhat_v1.md

As suggested, fr translate for nadhat_v1 board

fr translation for nadhat_v1.md

---

src/de/translate/phat-dac.md

Berry gatherer patch 1

---

src/de/template/pinout.yaml

Fixed a typo in german

---

src/es/translate/adafruit-oled-bonnet.md
src/es/translate/adafruit-pi-oled.md
src/es/translate/adafruit_matrix_bonnet.md
src/es/translate/aiy-vision-bonnet.md
src/es/translate/aiy-voice-bonnet.md
src/es/translate/audioplus.md
src/es/translate/audioplus_speakerplus.md
src/es/translate/audioplus_speakerplus_micplus.md
src/es/translate/breakout-garden-hat.md
src/es/translate/cube-bit-base.md

Boards A-C translated to Spanish

Boards A-C translated

---

common/page.html
resources/pinout.scss
resources/pinout.scss.css

- links into category if available
- if there is no directory, links to the first relevant entry within
page (e.g. 5V category)
Things to rework in future:
- category for GPIO, 5V, 3.3V
Thanks!

Make legend entries into links. See #308

---

src/es/translate/ab-1-wire-pi-plus.md
src/es/translate/ab-1-wire-pi-zero.md
src/es/translate/ab-adc-differential-pi.md
src/es/translate/ab-adc-pi.md
src/es/translate/ab-adcdac-pi-zero.md
src/es/translate/ab-expander-pi.md
src/es/translate/ab-io-pi-plus.md
src/es/translate/ab-io-pi-zero.md
src/es/translate/ab-rs485-pi.md
src/es/translate/ab-rtc-pi.md
src/es/translate/ab-serial-pi-plus.md
src/es/translate/ab-serial-pi-zero.md
src/es/translate/ab-servo-pwm-pi-zero.md

Boards from manufacturer AB UK translated

Boards AB translated

---

Dockerfile
README.md

* Add "Running in Docker" subsection to README.md

Add Dockerfile for containerized webserver

---

src/en/template/index.md

Update index.md to provide orientation information

---

src/en/template/footer.html

"Pinouyt.xyz" --> "Pinout.xyz"

Fix typo in footer.html

---

common/page.html

just in case someone has a Pi 4, not too much really

add HDMI port(s) for Pi 4

---

src/en/overlay/uart.md

Adds Raspberry Pi 4 UART pins.

Adding Raspberry Pi 4 UART pins

---

src/de/overlay/ground.md
src/de/overlay/i2c.md
src/de/overlay/uart.md

Fixes some translations to german

German translation fixes

---

src/en/overlay/iface-pwm.md

Add extra pin to PWM section

---

src/en/template/index.md

Too many hats are supported now... I counted 209.

---

src/de/translate/voice-hat.md
src/en/pin/pin-38.md

my first PR for this project, so please let me know if there's anything I should update!
Thanks!

Voice Hat: "I2C"->"I2S" and add Pin 38

---

src/en/overlay/pimoroni-enviro-plus.md

Typo in 'mic i2c data' ; should read 'mic i2s data'

Mic data comes via i2S not i2C

---

src/de/translate/unicorn-phat.md
src/en/overlay/unicorn-phat.md
src/es/overlay/unicorn-phat.md
src/fr/translate/unicorn-phat.md
src/it/translate/unicorn-phat.md
src/tr/translate/unicorn-phat.md

Fixes a small typo that I ran into this morning.
I wasn't sure how translation works in this repo... but if the example code is simply copied across - then those markdown files will need to be updated too. Let me know.

Fix example for unicorn pHAT
